# apiVersion: datadoghq.com/v2alpha1
# kind: DatadogAgent
# metadata:
#   name: datadog
# spec:
#   global:
#     credentials:
#       apiSecret:
#         secretName: datadog-secret
#         keyName: api-key

apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: myCluster
    registry: gcr.io/datadoghq
    site: datadoghq.com
    tags:
      - env:dev
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  features:
    apm:
      instrumentation:
        enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    npm:
      enabled: true
    liveContainerCollection:
      enabled: true
    orchestratorExplorer:
      enabled: true


# apiVersion: datadoghq.com/v2alpha1
# kind: DatadogAgent
# metadata:
#   name: datadog
# spec:
#   global:
#     clusterName: myCluster
#     registry: gcr.io/datadoghq
#     site: datadoghq.com
#     tags:
#       - env:dev
#     credentials:
#       apiSecret:
#         secretName: datadog-secret
#         keyName: api-key
#   features:
#     apm:
#       instrumentation:
#         enabled: true
#     liveContainerCollection:
#       enabled: true
#     orchestratorExplorer:
#       enabled: true
#   override:
#     agents:
#       containers:
#         processAgent:
#           env:
#             - name: "DD_ORCHESTRATOR_EXPLORER_EXTRA_TAGS"
#               value: "tag1:value1 tag2:value2"
#     clusterAgent:
#       env:
#         - name: "DD_ORCHESTRATOR_EXPLORER_EXTRA_TAGS"
#           value: "tag1:value1 tag2:value2"
